# ATHENA // JARVIS Kitty

font_family JetBrainsMono Nerd Font
font_size 10

background_opacity 0.88
dynamic_background_opacity yes

window_padding_width 12
confirm_os_window_close 0

cursor_shape beam
cursor_blink_interval 0.6

enable_audio_bell no
visual_bell_duration 0.0

foreground #cfe8ff
background #05070d
selection_foreground #05070d
selection_background #00c3ff

cursor #00c3ff
url_color #38bdf8

color0  #05070d
color1  #ff4d6d
color2  #00ffcc
color3  #ffd166
color4  #00c3ff
color5  #9b5cff
color6  #38d9ff
color7  #cfe8ff

color8  #334155
color9  #ff6b8a
color10 #5fffe0
color11 #ffe08a
color12 #5ad7ff
color13 #b58cff
color14 #7ee7ff
color15 #ffffff

tab_bar_edge top
tab_bar_style powerline
active_tab_foreground #05070d
active_tab_background #00c3ff
inactive_tab_foreground #cfe8ff
inactive_tab_background #0b1220